### ISSUE TITLE
ulauncher extension issue

### ISSUE THREAD

**Issue by premier69** [matheusfillipe/joplin-snippets#2]
hi

i can add others but this "https://ext.ulauncher.io/-/github-matheusfillipe-joplin-snippets" doesn't seem to work, nothing gets added to ulauncher.

**Comment by matheusfillipe** [comment]
Thanks for reporting! I had the wrong branch name on versions.json (master instead of main, thanks github). Fixed on 07201abfc1b68a0f04be3248774e567e8f107a5c.
